# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-11 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '博客',
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '菜单',
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000, verbose_name='内容')),
                ('subject', models.CharField(max_length=100, verbose_name='主题')),
                ('status', models.IntegerField(choices=[(0, '等待处理'), (1, '预约成功'), (2, '取消订单'), (3, '拒绝订单'), (4, '已完成订单')], default=0, verbose_name='订单状态')),
                ('time', models.DateTimeField()),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='订单时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name_plural': '预约表',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'TEAM',
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('gender', models.IntegerField(choices=[(0, '保密'), (1, '男'), (2, '女')], default=0, null=True, verbose_name='性别')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('phonenum', models.CharField(max_length=11, verbose_name='手机号码')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('fullname', models.CharField(max_length=100, verbose_name='真实姓名')),
                ('cost', models.IntegerField(null=True, verbose_name='总花费')),
                ('score', models.IntegerField(null=True, verbose_name='积分')),
            ],
            options={
                'verbose_name_plural': '用户表',
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.User', verbose_name='用户名'),
        ),
    ]
