# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-11 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='person',
            field=models.IntegerField(choices=[(1, '1-2人'), (2, '3-4人'), (3, '5-8人'), (4, '8人以上')], default=1, verbose_name='用餐人数'),
        ),
        migrations.AlterField(
            model_name='order',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发送订单时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(verbose_name='预约用餐时间'),
        ),
    ]
